config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resource :search, only: [:show]
  resources :users, only: [:new, :create, :edit, :update] do 
    resources :thoughts, only: [:create, :destroy]
    resources :photos, only: [:index]
    resource :friendship, only: [:create, :destroy]
  end

  resources :messages, only: [:create]
  resources :friendships, only: [] do
    resource :accepted_friendship, only: [:create]
  end
  resources :thoughts, only: [] do
    resource :like, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :photos, only: [:create, :show] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :comments, only: [] do
    resource :like, only: [:create, :destroy]
  end

  root to: "dashboards#show"

  get ":slug", to: "users#show", as: :user_show
end

app/models/thought.rb
class Thought < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :liked_object, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  def self.newest_first
    order("created_at DESC")
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  def create
    receiver = User.friendly.find(params[:user_id])
    @my_thoughts = current_user.thoughts
    @photo = Photo.new
    @thought = current_user.thoughts.new(thought_params.merge(receiver_id: receiver.id))

    if @thought.save
      redirect_to :back
    else
      render "app/views/dashboards/show"
    end
  end
  
  private

    def thought_params
      params.require(:thought).permit(
        :body,
      )
    end
end

app/views/thoughts/_thought.html.erb
<div class="individual_thought">
  <div class="feed_profile_images"><%= link_to image_tag(thought.user.profile_picture.url(:thumbnail)), user_show_path(thought.user) %></div>
  <div class="user_name_thought"><%= link_to thought.user.name, user_show_path(thought.user) %></div>
  <div><%= thought.body %></div>
  <div class="information">
    <%= time_ago_in_words(thought.created_at) %> ago
  </div>
  <%= render "like_button", object: thought %>
</div>
<div>
  <div class="thought-comments-dashboard" id="thought-comments-dashboard-<%= thought.id %>">
    <ul>
      <% thought.comments.each do |comment| %>
        <li>
          <%= render comment %>
        </li>
      <% end %>
    </ul>
  </div>
</div>